### ISSUE TITLE
Add precipitation chances

### ISSUE THREAD

**Issue by djensenius** [djensenius/FluxHaus#22]
Add some text about when it might rain or snow somewhere.
```[tasklist]
### Tasks
- [ ] https://github.com/djensenius/FluxHaus/issues/23
- [ ] https://github.com/djensenius/FluxHaus/issues/24
- [ ] https://github.com/djensenius/FluxHaus/issues/25
- [ ] https://github.com/djensenius/FluxHaus/issues/26
```
